version: "3.8"

services:
  nginx:
    build:
      context: nginx
    image: django5-boiler-nginx:latest
    env_file: settings.env
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -sf localhost:80/health-check || exit 1"]
    #  interval: 10s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 10s
    volumes:
      - data_dir:/data
    secrets:
      - source: cssnr_basic_http_auth
        target: /etc/nginx/auth.users
    depends_on:
      - app
      - flower
      - redis-commander
      - phpmyadmin
    ports:
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: nginx

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: django5-boiler-app:latest
    env_file: settings.env
    #command: "watchmedo auto-restart -d /app -p '*.py;*.html' -R -- gunicorn project.asgi:application -b 0.0.0.0:9000 -w 1 -k uvicorn.workers.UvicornWorker"
    #command: "gunicorn project.asgi:application -b 0.0.0.0:9000 -w 1 -k uvicorn.workers.UvicornWorker --reload"
    command: "uvicorn project.asgi:application --host 0.0.0.0 --port 9000 --reload --reload-include *.html"
    #command: "sh -c 'python manage.py runserver 0.0.0.0:9000'"
    #healthcheck:
    #  test: ["CMD", "curl", "-sf", "http://localhost:9000/app-health-check/"]
    #  interval: 1m
    #  timeout: 10s
    #  retries: 3
    #  start_period: 10s
    deploy:
      mode: global
      resources:
        limits:
          cpus: "2.0"
          memory: 256M
    volumes:
      - data_dir:/data
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: app
          target: app
        #- action: sync+exec
        #  path: app/templates
        #  target: app/templates
        #  exec:
        #    command: "pkill -HUP gunicorn"
        - action: sync+exec
          path: app/static
          target: app/static
          exec:
            command: "python manage.py collectstatic --noinput -v 0"
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock

  worker:
    image: django5-boiler-app:latest
    env_file: settings.env
    command: "celery -A project worker -l INFO -c 2"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 256M
    #volumes:
    #  - data_dir:/data
    depends_on:
      - redis
    develop:
      watch:
        - action: restart
          path: app/**/*.py

  beat:
    image: django5-boiler-app:latest
    env_file: settings.env
    command: "celery -A project beat -l INFO -S django"
    deploy:
      replicas: 1
    depends_on:
      - redis
      - worker

  redis:
    image: redis:6-alpine
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
    volumes:
      - redis_data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0,local:redis:6379:1
      - URL_PREFIX=/redis
      - TRUST_PROXY=true
    deploy:
      replicas: 1
    depends_on:
      - redis

  flower:
    image: mher/flower:1.2
    env_file: settings.env
    command: "celery flower --enable_events=False --url_prefix=flower"
    deploy:
      replicas: 1
    volumes:
      - flower_data:/data
    depends_on:
      - app
      - redis
      - worker

  phpmyadmin:
    image: phpmyadmin:latest
    env_file: settings.env
    environment:
      - APACHE_PORT=8082
      - PMA_ABSOLUTE_URI=/phpmyadmin/
      - PMA_HOST=${DATABASE_HOST}
      - PMA_PORT=${DATABASE_PORT}
      - PMA_USER=${DATABASE_USER}
      - PMA_PASSWORD=${DATABASE_PASS}
    deploy:
      replicas: 1

secrets:
  cssnr_basic_http_auth:
    file: ~/basic_http_auth

volumes:
  data_dir:
  flower_data:
  redis_data:
