version: "3.8"

services:
  nginx:
    build:
      context: nginx
    image: ghcr.io/smashedr/django5-boiler-nginx:${VERSION:-latest}
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.STACK_NAME-http.rule=Host(`${TRAEFIK_HOST:?err}`)"
        - "traefik.http.routers.STACK_NAME-http.entrypoints=http"
        - "traefik.http.routers.STACK_NAME-http.middlewares=https-redirect"
        - "traefik.http.routers.STACK_NAME-https.rule=Host(`${TRAEFIK_HOST:?err}`)"
        - "traefik.http.routers.STACK_NAME-https.entrypoints=https"
        - "traefik.http.routers.STACK_NAME-https.tls=true"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.port=80"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.scheme=http"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - data_dir:/data
    secrets:
      - source: cssnr_basic_http_auth
        target: /etc/nginx/auth.users
    depends_on:
      - app
      - flower
      - redis-commander
      - phpmyadmin
    networks:
      - traefik-public
      - internal

  app:
    build:
      context: app
    image: ghcr.io/smashedr/django5-boiler-app:${VERSION:-latest}
    #env_file: stack.env
    command: "gunicorn project.asgi:application -b 0.0.0.0:9000 -w 2 -k uvicorn.workers.UvicornWorker"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9000/app-health-check/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      resources:
        limits:
          cpus: "2.0"
          memory: 128M
    volumes:
      - data_dir:/data
    depends_on:
      - redis
    networks:
      - internal

  worker:
    image: ghcr.io/smashedr/django5-boiler-app:${VERSION:-latest}
    #env_file: stack.env
    command: "celery -A project worker -l INFO -c 2"
    deploy:
      replicas: 1
    #volumes:
    #  - data_dir:/data
    depends_on:
      - redis
    networks:
      - internal

  beat:
    image: ghcr.io/smashedr/django5-boiler-app:${VERSION:-latest}
    #env_file: stack.env
    command: "celery -A project beat -l INFO -S django"
    deploy:
      replicas: 1
    depends_on:
      - redis
      - worker
    networks:
      - internal

  redis:
    image: redis:6-alpine
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
    volumes:
      - redis_data:/data
    networks:
      - internal

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0,local:redis:6379:1
      - URL_PREFIX=/redis
      - TRUST_PROXY=true
    deploy:
      replicas: 1
    depends_on:
      - redis
    networks:
      - internal

  flower:
    image: mher/flower:1.2
    #env_file: stack.env
    command: "celery flower --enable_events=False --url_prefix=flower"
    deploy:
      replicas: 1
    volumes:
      - flower_data:/data
    depends_on:
      - app
      - redis
      - worker
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:latest
    #env_file: stack.env
    environment:
      - APACHE_PORT=8082
      - PMA_ABSOLUTE_URI=/phpmyadmin/
      - PMA_HOST=${DATABASE_HOST}
      - PMA_PORT=${DATABASE_PORT}
      - PMA_USER=${DATABASE_USER}
      - PMA_PASSWORD=${DATABASE_PASS}
    deploy:
      replicas: 1
    networks:
      - internal

networks:
  internal:
    driver: overlay
  traefik-public:
    external: true

secrets:
  cssnr_basic_http_auth:
    external: true

volumes:
  data_dir:
  flower_data:
  redis_data:
#    driver_opts:
#      type: none
#      o: bind
#      device: /data/docker/STACK_NAME
