# Generated by Django 5.1.11 on 2025-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="access_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="refresh_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
