name: "Build"

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      GHCR_USER:
        required: true
        type: string
      STACK_FILE:
        required: false
        type: string
        default: docker-compose-swarm.yaml
    secrets:
      GHCR_PASS:
        required: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node 20"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Set Cache Directory"
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: "Node Cache"
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Node Cache Hit"
        if: ${{ steps.npm-cache.outputs.cache-hit }}
        run: |
          echo "dir: '${{ steps.npm-cache-dir.outputs.dir }}'"
          echo "cache-hit: '${{ steps.npm-cache.outputs.cache-hit }}'"

      - name: "Install Node"
        run: |
          npm install

      - name: "Update SW Cache Version"
        env:
          SERVICE_WORKER: app/static/js/sw.js
        run: |
          echo "Updating SW Cache to: v${GITHUB_RUN_NUMBER}"
          sed -i "0,/v1/s//v${GITHUB_RUN_NUMBER}/" ${SERVICE_WORKER}
          head ${SERVICE_WORKER} -n 4

      #- name: "Debug"
      #  run: |
      #    pwd
      #    ls
      #    ls -lAh app/static
      #    head app/static/js/sw.js -n 4

      - name: "TESTING Docker Tags"
        id: dtags
        uses: cssnr/docker-tags-action@v1
        with:
          tags: ${{ inputs.VERSION }}
          images: "ghcr.io/${{ github.repository }}"

      - name: "TESTING Debug Docker Tags"
        run: |
          echo inputs.VERSION: '${{ inputs.VERSION }}'
          echo github.ref_name: '${{ github.ref_name }}'
          echo -e "tags:\n${{ steps.dtags.outputs.tags }}"
          echo -e "labels:\n${{ steps.dtags.outputs.labels }}"

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ inputs.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Bake and Push"
        uses: docker/bake-action@v6
        with:
          files: ${{ inputs.STACK_FILE }}
          source: .
          push: true
          targets: app,nginx
          set: |
            app.tags=ghcr.io/${{ github.repository }}-app:${{ inputs.VERSION }}
            nginx.tags=ghcr.io/${{ github.repository }}-nginx:${{ inputs.VERSION }}
            *.platform=linux/amd64,linux/arm64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
