name: "Cleanup"

on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true

jobs:
  cleanup:
    name: "Cleanup"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Purge Cache"
        uses: cssnr/cloudflare-purge-cache-action@v2
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domains: cssnr.com
