name: "CI"

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Run Build"
        type: boolean
        default: true
      deploy:
        description: "Run Deploy"
        type: boolean
        default: true
      cleanup:
        description: "Run Cleanup"
        type: boolean
        default: true
      env:
        description: "Environment to Deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

  push:
    branches-ignore:
      - master
    paths:
      - ".github/workflows/ci.yaml"
      - "app/**"
      - "nginx/**"
      - "gulpfile.js"
      - "package.json"
      - "package-lock.json"
      - "pyproject.toml"
      - "docker-compose-swarm.yaml"

env:
  stack-name: "${{ inputs.env || 'dev' }}_${{ github.repository }}"
  env-name: "${{ inputs.env || 'dev' }}"

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug"
        run: |
          echo inputs.build: ${{ inputs.build }}
          echo inputs.deploy: ${{ inputs.deploy }}
          echo env.stack-name: ${{ env.stack-name }}
          echo env.env-name: ${{ env.env-name }}
          echo github.event_name: ${{ github.event_name }}

      # BEGIN Custom - move to custom workflow

      - name: "Setup Node 20"
        if: ${{ github.event_name == 'push' && true || inputs.build }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Set Cache Directory"
        if: ${{ github.event_name == 'push' && true || inputs.build }}
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: "Node Cache"
        if: ${{ github.event_name == 'push' && true || inputs.build }}
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Node Cache Hit"
        if: ${{ steps.npm-cache.outputs.cache-hit }}
        run: |
          echo "dir: '${{ steps.npm-cache-dir.outputs.dir }}'"
          echo "cache-hit: '${{ steps.npm-cache.outputs.cache-hit }}'"

      - name: "Install Node"
        if: ${{ github.event_name == 'push' && true || inputs.build }}
        run: |
          npm install

      - name: "Update SW Cache Version"
        if: ${{ github.event_name == 'push' && true || inputs.build }}
        env:
          SERVICE_WORKER: app/static/js/sw.js
        run: |
          echo "Updating SW Cache to: v${GITHUB_RUN_NUMBER}"
          sed -i "0,/v1/s//v${GITHUB_RUN_NUMBER}/" ${SERVICE_WORKER}
          head ${SERVICE_WORKER} -n 4

      # END Custom - move to custom workflow

      - name: "Swarm Build Action"
        if: ${{ github.event_name == 'push' && true || inputs.build }}
        uses: ./.github/actions/build
        with:
          version: ${{ env.env-name }}
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Portainer Deploy Action"
        if: ${{ github.event_name == 'push' && true || inputs.deploy }}
        uses: ./.github/actions/deploy
        with:
          version: ${{ env.env-name }}
          stack-name: ${{ env.stack-name }}
          config-file: services/shane/django5-boiler/${{ env.env-name }}.env
          config-ssh-key: ${{ secrets.SERVICE_CONFIGS_KEY }}
          portainer-url: ${{ secrets.PORTAINER_URL }}
          portainer-token: ${{ secrets.PORTAINER_TOKEN }}

      - name: "Purge Cache"
        if: ${{ github.event_name == 'push' && true || inputs.cleanup }}
        uses: cssnr/cloudflare-purge-cache-action@v2
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domains: cssnr.com
