name: "CI"

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Tag to Deploy"
        type: string
        required: true
        default: "dev"

  push:
    branches-ignore:
      - master
    paths:
      - ".github/workflows/ci.yaml"
      - "app/**"
      - "nginx/**"
      - "gulpfile.js"
      - "package.json"
      - "package-lock.json"
      - "pyproject.toml"
      - "docker-compose-swarm.yaml"

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node 20"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Set Cache Directory"
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: "Node Cache"
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Node Cache Hit"
        if: ${{ steps.npm-cache.outputs.cache-hit }}
        run: |
          echo "dir: '${{ steps.npm-cache-dir.outputs.dir }}'"
          echo "cache-hit: '${{ steps.npm-cache.outputs.cache-hit }}'"

      - name: "Install Node"
        run: |
          npm install

      - name: "Update SW Cache Version"
        env:
          SERVICE_WORKER: app/static/js/sw.js
        run: |
          echo "Updating SW Cache to: v${GITHUB_RUN_NUMBER}"
          sed -i "0,/v1/s//v${GITHUB_RUN_NUMBER}/" ${SERVICE_WORKER}
          head ${SERVICE_WORKER} -n 4

      - name: "Docker Build"
        uses: ./.github/actions/build
        with:
          version: ${{ inputs.VERSION != '' && inputs.VERSION || 'dev' }}
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Portainer Deploy"
        uses: ./.github/actions/deploy
        with:
          version: ${{ inputs.VERSION != '' && inputs.VERSION || 'dev' }}
          stack-name: dev_cssnr-django5-boiler
          stack-file: docker-compose-swarm.yaml
          config-file: services/shane/django5-boiler/dev.env
          portainer-url: ${{ secrets.PORTAINER_URL }}
          portainer-token: ${{ secrets.PORTAINER_TOKEN }}

      - name: "Purge Cache"
        uses: cssnr/cloudflare-purge-cache-action@v2
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domains: cssnr.com
