name: "Dev Deploy"

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: "Tag to Deploy"
        type: string
        required: true
        default: "dev"
      CLEANUP:
        description: "Run Cleanup Steps"
        type: boolean
        required: true
        default: true

jobs:
  deploy:
    name: "Deploy"
    uses: ./.github/workflows/deploy.yaml
    permissions:
      contents: read
    with:
      GHCR_TAG: ${{ inputs.TAG }}
      STACK_NAME: dev_django5-boiler
      STACK_FILE: docker-compose-swarm.yaml
      CONFIG_FILE: services/shane/django5-boiler/dev.env
    secrets:
      SERVICE_CONFIGS_KEY: ${{ secrets.SERVICE_CONFIGS_KEY }}
      PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
      PORTAINER_TOKEN: ${{ secrets.PORTAINER_TOKEN }}

  cleanup:
    name: "Cleanup"
    uses: ./.github/workflows/cleanup.yaml
    needs: deploy
    if: ${{ inputs.CLEANUP != '' && inputs.CLEANUP || true }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
