name: "Test"

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/test.yaml"
      - "app/**"
      - "nginx/**"
      - "test.env"
      - "gulpfile.js"
      - "package.json"
      - "package-lock.json"
      - "pyproject.toml"
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}

    services:
      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: testdb
          MARIADB_USER: testdb
          MARIADB_PASSWORD: password123
          MARIADB_RANDOM_ROOT_PASSWORD: 1
        options: >-
          --health-cmd "mariadb-admin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Install UV"
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

      - name: "Install Python"
        run: |
          uv python install

      - name: "Install Project"
        run: |
          uv sync --locked --all-extras --dev

      - name: "Setup Node 24"
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: "Install Node"
        run: |
          npm ci

      - name: "Debug UV"
        continue-on-error: true
        run: |
          echo "group: ${{ github.workflow }}-${{ github.ref }}"

          echo "github.workflow: ${{ github.workflow }}"
          echo "github.ref: ${{ github.ref }}"
          echo "pull_request.number: ${{ github.event.pull_request.number }}"

          uv python dir
          uv python find
          uv run python -V
          echo "::group::uv tree"
          uv tree
          echo "::endgroup::"
          echo "::group::uv pip list"
          uv pip list
          echo "::endgroup::"

      #- name: "Checkout Service Configs"
      #  uses: actions/checkout@v4
      #  with:
      #    repository: "hosted-domains/service-configs"
      #    ssh-key: ${{ secrets.SERVICE_CONFIGS_KEY }}
      #    ref: master
      #    path: service-configs
      #    sparse-checkout: |
      #      services/${{ github.repository_owner }}/${{ github.event.repository.name }}/dev.env
      #    sparse-checkout-cone-mode: false

      - name: "Test Migrations"
        working-directory: app
        run: |
          set -a
          source ../test.env
          #uv run python manage.py makemigrations --dry-run --check --noinput
          uv run python manage.py migrate

      - name: "Test App"
        id: test
        working-directory: app
        run: |
          set -a
          source ../test.env
          uv run coverage run --rcfile=../pyproject.toml manage.py test --verbosity 2 --keepdb
          uv run coverage xml

      - name: "Coverage Report"
        working-directory: app
        run: |
          uv run coverage report -m

      - name: "codecov"
        if: ${{ !cancelled() && steps.test.outcome == 'success' }}
        continue-on-error: true # will fail if external PR due to secrets
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app/coverage.xml

      #- name: "Codacy Coverage"
      #  uses: codacy/codacy-coverage-reporter-action@v1
      #  with:
      #    project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #    coverage-reports: app/coverage.xml
